version: "3.9"

services:
  hawkmoth-app-pandas-matplotlib:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hawkmoth-demo-pandas-matplotlib
    ports:
      - "8502:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ENABLECORS=false
      - STREAMLIT_SERVER_ENABLEXSRFPROTECTION=false
      - STREAMLIT_SERVER_HEADLESS=true
    restart: unless-stopped
